global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['172.17.0.1:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
